### ISSUE TITLE
Unable to parse version that ends with `~`

### ISSUE THREAD

**Issue by sbrunner** [nexB/debian-inspector#39]
Get the version from https://packages.debian.org/bookworm/ruby-prawn.

```python
import debian_inspector.version
debian_inspector.version.Version.from_string('2.4.0+dfsg-1~')
```
=>
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sbrunner/.pyenv/versions/3.11.9/lib/python3.11/site-packages/debian_inspector/version.py", line 141, in from_string
    raise ValueError('Invalid version string: "{}"'.format(version))
ValueError: Invalid version string: "2.4.0+dfsg-1~"
```
Expected result:
```
Version(epoch=0, upstream='2.4.0+dfsg', revision='1~')
```

**Comment by pombredanne** [comment]
@sbrunner Thanks for the report! ... this trailing tilde is a weird thing, but that's a valid one.

Can I interest you in a patch?  :innocent: 


Reminder to self: there is a copy of the same parsing code in https://github.com/nexB/univers/blob/main/src/univers/debian.py and this was originally forked from @xolox https://github.com/xolox/python-deb-pkg-tools/tree/master/deb_pkg_tools/version which may have the same issue.

**Comment by pombredanne** [comment]
I added https://github.com/nexB/univers/issues/133 as follow up in "univers"
