### ISSUE TITLE
encoding issue when using `copyright.DebianCopyright.from_file`

### ISSUE THREAD

**Issue by chinyeungli** [nexB/debian-inspector#4]
I created parser using the `debut` library with the following code
```
data = copyright.DebianCopyright.from_file(input).to_dict()
```
However, this line of code fail with encoding error for some files
```
'ascii' codec can't decode byte 0xe2 in position 17: ordinal not in range(128)
```

Some sample files are:
https://changelogs.ubuntu.com/changelogs/pool/main/d/dpkg/dpkg_1.19.0.5ubuntu2/copyright
https://changelogs.ubuntu.com/changelogs/pool/main/d/dpkg/dpkg_1.19.0.5ubuntu2/copyright

**Comment by pombredanne** [comment]
This is now fixed with this https://github.com/nexB/debian-inspector/commit/75ab6a4d64a4ff3270018728cd3df325d2870cb2 on Python 3.
