### ISSUE TITLE
Determine the primary license from a copyright file

### ISSUE THREAD

**Issue by pombredanne** [nexB/debian-inspector#8]
This should be based on the `Files: *` present in a paragraph.
This would become really handy as Debian copyright are erring on the comprehensive and verbose side. And knowing the primary license would help deal with the data density better!

**Comment by AyanSinhaMahapatra** [comment]
This is now implemented and available at https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/debian_copyright.py#L615, closing.
