### ISSUE TITLE
RFC: Renaming to debian-inspector

### ISSUE THREAD

**Issue by pombredanne** [nexB/debian-inspector#9]
In keeping up with simpler descriptive and generic project names, I would like to rename this repo to debian-inspector (and we are getting also rpm-inspector and container-inspector and several upcoming ones to be extracted from https://github.com/nexB/scancode-toolkit/tree/develop/src/packagedcode as their own libraries)

**Comment by mjherzog** [comment]
+1

**Comment by nishakm** [comment]
@pombredanne can you comment here when you release a PyPI package of the new name so we can consume it?

**Comment by pombredanne** [comment]
@nishakm sure thing! ... are you ok with it otherwise? I could keep some compat module in the new package name such that upgrade would be easy enough (I plan also to rename the python module)

**Comment by nishakm** [comment]
> @nishakm sure thing! ... are you ok with it otherwise? I could keep some compat module in the new package name such that upgrade would be easy enough (I plan also to rename the python module)

I am OK with it. Including @rnjudge for visibility.

**Comment by pombredanne** [comment]
The repo has been renamed to https://github.com/nexB/debian-inspector for a start and https://github.com/nexB/debut redirects there. Next up will be the code updates and a new PyPI release, may be a 1.0? :innocent:

**Comment by pombredanne** [comment]
https://pypi.org/project/debian-inspector/0.9.10/ has been released as renamed with extra bug fixes, dropping support for Python 2.
And a legacy compat "debut" module meaning that replacing debug by debian-inspector may require no code change for now. The debut legacy module is marked as deprecated though.
Thank you all for the input!
